### PR TITLE
feat: support for plasma-apply-desktoptheme

### PR DESCRIPTION
**Pull request by benben962**
Added a new yml option to change the desktop theme along with other plasma changes. It uses the plasma-apply-desktoptheme command to apply a new theme.

### CODE REVIEW

**Comment by justjokiing** [comment]
Thanks for the commit! I just quickly looked through your commit and it looks good.

I will test soon and hopefully merge.

**Comment by justjokiing** [comment]
I think I just need you to add the command line arguments for the desktop theme switching.

**Comment by benben962** [comment]
Hey! Thanks for the quick reaction! I'm not sure where you want me to put the command line arguments?

**Comment by justjokiing** [comment]
Can you test these changes?

**Comment by benben962** [comment]
Sorry for the bi-commit, I messed up with my local git install! I tested it and added the necessary changes in order for it to work on my installation.

**Comment by justjokiing** [comment]
Sorry for the delay, thank you very much for your work.

**Pull request merged**
